// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package persistence

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) error
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	GetActiveProducts(ctx context.Context) ([]Product, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetProductsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Product, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
}

var _ Querier = (*Queries)(nil)
