// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package persistence

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountActiveUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
